//This file is automatically generated. DO NOT EDIT!

#include <RobotRaconteur.h>
#include <boost/signals2.hpp>
#include "edu__rpi__cats__sensors__camera_interface.h"
#pragma once

namespace example
{
namespace webcam
{

class Webcam;

class Webcam : public virtual edu::rpi::cats::sensors::camera_interface::Camera
{
public:
virtual uint8_t get_camera_found()=0;
virtual void set_camera_found(uint8_t value)=0;

virtual RR_SHARED_PTR<edu::rpi::cats::sensors::camera_interface::Image > getCurrentImage()=0;

virtual RR_SHARED_PTR<edu::rpi::cats::sensors::camera_interface::ImageHeader > getImageHeader()=0;

virtual void StartStreaming()=0;

virtual void StopStreaming()=0;

virtual RR_SHARED_PTR<RobotRaconteur::Pipe<RR_SHARED_PTR<edu::rpi::cats::sensors::camera_interface::Image > > > get_ImageStream()=0;
virtual void set_ImageStream(RR_SHARED_PTR<RobotRaconteur::Pipe<RR_SHARED_PTR<edu::rpi::cats::sensors::camera_interface::Image > > > value)=0;

virtual std::string RRType() {return "example.webcam.Webcam";  }
};

}
}

